### ISSUE TITLE
Partner: Status of candidates are not updating correctly in dashboard

### ISSUE THREAD

**Issue by Tatireddysreevani** [rkulkar5/OnlineTAT#242]
For test(candidate name) I gave final result as “Not suitable” in partner interview
![image](https://user-images.githubusercontent.com/61975055/94790786-6537ee80-03f4-11eb-90aa-091928bf02ce.png)

But in dashboard of partner queue result is showing as pending…
![image](https://user-images.githubusercontent.com/61975055/94790829-75e86480-03f4-11eb-989a-f13d87eddd67.png)

For test1 I gave final result as “not suitable” in sme queue for technical interview
![image](https://user-images.githubusercontent.com/61975055/94790968-a7f9c680-03f4-11eb-81f5-4585051fae07.png)

In Dashboard of partner queue it is showing pending…..
![image](https://user-images.githubusercontent.com/61975055/94791031-bc3dc380-03f4-11eb-9eaf-d6553b470e93.png)

here when we gave result as "not suitable", it is showing as pending in dashboard but when we gave "recommended" and "strongly recommended", it is showing as it is in dashboard.
My doubt is why it is not showing "not suitable" result in dashboard of partner interview

**Comment by Adharshd** [comment]
@rashmidevapura : Can you please check the same?

**Comment by rashmidevapura** [comment]
Fixed ..checked in..please test once deployed in cloud

**Comment by Tatireddysreevani** [comment]
ok Rashmi

**Comment by Tatireddysreevani** [comment]
will check and inform back

**Comment by Tatireddysreevani** [comment]
still facing the same issue.
![image](https://user-images.githubusercontent.com/61975055/95064377-4780c700-071d-11eb-9f9c-cccc2398992a.png)
here i gave technical interview result as "not Suitable" for candidate_vani7, but showing as pending
if we click on view details, we are able to see the result as not suitable
![image](https://user-images.githubusercontent.com/61975055/95064637-a0e8f600-071d-11eb-9786-2288fbbb95ca.png)

**Comment by rashmidevapura** [comment]
![image](https://user-images.githubusercontent.com/61687054/95065623-f07bf180-071e-11eb-8ad0-da4c8c64cb3b.png)

**Comment by Tatireddysreevani** [comment]
is it in cloud Rashmi

**Comment by rashmidevapura** [comment]
![image](https://user-images.githubusercontent.com/61687054/95066088-8d3e8f00-071f-11eb-998a-faa85854c57d.png)
its in local....working fine.... wait for new deployment and test

**Comment by rashmidevapura** [comment]
try for new candidate and check

**Comment by Tatireddysreevani** [comment]
ok rashmi

**Comment by Tatireddysreevani** [comment]
Issue resolved
